/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entities.Tracker;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import service.TrackerService;

/**
 *
 * @author zidah
 */
public class ChartsForm extends javax.swing.JInternalFrame {
private static final ChartsForm instane =new ChartsForm();
private TrackerService ts;
    /**
     * Creates new form ChartsForm
     */
    private ChartsForm() {
        initComponents();
        ts = new TrackerService();
        loadCharts();
    }
    
 public static final ChartsForm getInstance() {
  		return instane ;
  	}
 private int countpPosition(Tracker tracker ){
     try {
            String req = "SELECT COUNT(*) FROM position WHERE position.idTracker=? ";
           PreparedStatement pr = connexion.Connexion.getConnection().prepareStatement(req);
            pr.setInt(1, tracker.getId());
            
            ResultSet rs = pr.executeQuery();
           
            while (rs.next()) {
                //System.out.println(rs.getInt("id"));
               
                return rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
     
     return 0;
     
 }
    public void loadCharts(){
         DefaultCategoryDataset dod = new DefaultCategoryDataset();
         for (Tracker t : ts.findAll()) {
            
             dod.setValue(countpPosition(t), "nombre de positions ",t.getSimNumber() );
             
        }
        /* dod.setValue(78.80, "nombre de positions ","reda" );
         dod.setValue(80.12, "marks2","amiiine" );
         dod.setValue(50.80, "marks3","anass" );
         dod.setValue(98.80, "marks6","zikooo" );*/
         JFreeChart jchart = ChartFactory.createBarChart("rapport des positions", "simNumber du trackers","nombre de position", dod, PlotOrientation.VERTICAL,true, true, false);
         CategoryPlot plot = jchart.getCategoryPlot();
         plot.setRangeGridlinePaint(Color.BLACK);
         ChartFrame chartform = new ChartFrame("rapport des positions",jchart,true);
         //chartform.setVisible(true);
         //chartform.setSize(500,400);
         ChartPanel chartPanel = new ChartPanel(jchart);
         chartpanel.removeAll();
         chartpanel.add(chartPanel);
         chartpanel.updateUI();
         
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chartpanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-businessman-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(639, Short.MAX_VALUE))
        );

        chartpanel.setBackground(new java.awt.Color(255, 255, 255));
        chartpanel.setLayout(new javax.swing.BoxLayout(chartpanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chartpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chartpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
